### ISSUE TITLE
loco/loco should be a dependency

### ISSUE THREAD

**Issue by tonifisler** [antistatique/drupal-loco-translate#3]
Why is `loco/loco` not a dependency if the module "requires" it? This extra `composer require` step is really unnecessary.
 
![Screenshot 2019-06-17 at 09 27 10](https://user-images.githubusercontent.com/1708450/59586029-32c09000-90e2-11e9-8521-5b57e8f3e7f3.png)

**Comment by gido** [comment]
Sadly it's necessary for folk installing the module without composer (zip file from drupal.org or drush dl command).

We added `loco/loco` as a composer requirement so you don't need this step if you install the module via composer:

https://github.com/antistatique/drupal-loco-translate/blob/fccb400a0cc4fd47daec237ef26b26802d83e4ea/composer.json#L42-L44

**Comment by tonifisler** [comment]
I installed with Composer and still had this message though 🤔

**Comment by WengerK** [comment]
We can't see the swiftmailer module.

But we can show a warning during installation, it's already done when you use the Ui to enable a module via the `hook_requirements`, you can't install the module if you don't install the Loco Library.

Unfortunately, `drush` don't call this `hook_requirements` and Drupal don't expose any `hook_preinstall` - I just added a new Error message if you enable the module using Drush whitout having the proper library:

<img width="724" alt="Screenshot 2019-06-19 at 14 39 52" src="https://user-images.githubusercontent.com/1841592/59766351-529db280-92a0-11e9-9b81-370bca31754d.png">
