### ISSUE TITLE
Pull only 1 language

### ISSUE THREAD

**Issue by tonifisler** [antistatique/drupal-loco-translate#5]
You say:

> Bear in mind that this option is primarily intended for pulling single-language. 
> The status of asset translations is likely to differ between locales, so the result may not make sense.

And you are right. So let's not let the user select multiple languages and change the checkboxes to radios in Pull form.
http://watchdreamer.test/admin/config/regional/loco_translate/pull

**Comment by WengerK** [comment]
the current code has a loop that, well loop on each language. So it working as design
