### ISSUE TITLE
Flags filters are incorrect

### ISSUE THREAD

**Issue by tonifisler** [antistatique/drupal-loco-translate#6]
See https://localise.biz/help/glossary/flag#flags for available flags

**Should be:**
Translated
Untranslated
Fuzzy
Incorrect
Provisional
Unapproved
Incomplete
Rejected

![Screenshot 2019-06-17 at 09 39 11](https://user-images.githubusercontent.com/1708450/59586769-f0984e00-90e3-11e9-904b-bacd7e30e3ca.png)
http://watchdreamer.test/admin/config/regional/loco_translate/pull

**Comment by WengerK** [comment]
Resolved by de2a4b6
